In [1]:
#1. problem statement is Predict the Chronic Kidney disease based on several parameters
#2. Dataset has 25 columns and 399 rows
#3. For standardize the dataset preprocessing is require - get_dummies, standardscaler

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('CKD.csv')
dataset # column C, F, G, H, I, S, T, U, V, W, X, Y has nominal data
#column Y has output rest of them all are input

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset = pd.get_dummies(dataset, drop_first = True, dtype = int)
dataset #convert the nominal data into ordinal data

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
#seperate input and output
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
input = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
output = dataset[['classification_yes']]

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (input, output, test_size = 1/3, random_state = 0)

In [19]:
dataset [['classification_yes']].value_counts()#dataset is highly imbalanced
#dataset has 2 class class 1 = yes, class 0 = no

classification_yes
1                     249
0                     150
Name: count, dtype: int64

In [91]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [104]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
parameter = {  'loss': [ 'log_loss', 'modified_huber','squared_error', 
                        'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive'],
    'penalty': ['l2'],
    'alpha': [0.0001],
    'l1_ratio': [0.15],
    'fit_intercept': [True],
    'max_iter': [1000],
    'tol': [0.001],
    'shuffle': [True],
    'verbose': [0],
    'epsilon': [0.1],
    'n_jobs': [None],
    'random_state': [None],
    'learning_rate': ['optimal'],
    'eta0': [0.01],
    'power_t': [0.5],
    'early_stopping': [False],
    'validation_fraction': [0.1],
    'n_iter_no_change': [5],
    'class_weight': [None],
    'warm_start': [False],
    'average': [False]
    }
grid = GridSearchCV(SGDClassifier(), parameter, refit = True, verbose = 3, n_jobs = -1, scoring = 'f1_weighted')
grid.fit(x_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SGDClassifier(), n_jobs=-1,
             param_grid={'alpha': [0.0001], 'average': [False],
                         'class_weight': [None], 'early_stopping': [False],
                         'epsilon': [0.1], 'eta0': [0.01],
                         'fit_intercept': [True], 'l1_ratio': [0.15],
                         'learning_rate': ['optimal'],
                         'loss': ['log_loss', 'modified_huber', 'squared_error',
                                  'huber', 'epsilon_insensitive',
                                  'squared_epsilon_insensitive'],
                         'max_iter': [1000], 'n_iter_no_change': [5],
                         'n_jobs': [None], 'penalty': ['l2'], 'power_t': [0.5],
                         'random_state': [None], 'shuffle': [True],
                         'tol': [0.001], 'validation_fraction': [0.1],
                         'verbose': [0], 'warm_start': [False]},
             scoring='f1_weighted', verbose=3)

In [105]:
result = grid.cv_results_
grid_pred = grid.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_pred)
print (cm)

from sklearn.metrics import classification_report
clf = classification_report(y_test, grid_pred) 
print(clf)

[[50  1]
 [ 0 82]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        51
           1       0.99      1.00      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [106]:
#generate f1 score value
from sklearn.metrics import f1_score # to get the f1 score value
f1_macro = f1_score(y_test, grid_pred, average = 'weighted')
print("The f1_macro value for best parameter {}.". format(grid.best_params_), f1_macro)

The f1_macro value for best parameter {'alpha': 0.0001, 'average': False, 'class_weight': None, 'early_stopping': False, 'epsilon': 0.1, 'eta0': 0.01, 'fit_intercept': True, 'l1_ratio': 0.15, 'learning_rate': 'optimal', 'loss': 'log_loss', 'max_iter': 1000, 'n_iter_no_change': 5, 'n_jobs': None, 'penalty': 'l2', 'power_t': 0.5, 'random_state': None, 'shuffle': True, 'tol': 0.001, 'validation_fraction': 0.1, 'verbose': 0, 'warm_start': False}. 0.9924667654735397

In [107]:
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])
roc

0.9997608799617408